### ISSUE TITLE
Use OpenAIRE refresh token to grab a personal token for every run. 

### ISSUE THREAD

**Issue by FrancisTembo** [ClimateCompatibleGrowth/research_index_backend#16]
Instead of exporting the personal token as an environment variable, we can use a persistent refresh token to retrieve a new personal token for each run, since the personal token expires after one hour.

**Comment by willu47** [comment]
Note that refresh tokens expire after one month.  A local `.env` file containing the refresh token would be a good work around, rather than having to manually export the refresh token every console session. See https://pypi.org/project/python-dotenv/ for example.

**Comment by FrancisTembo** [comment]
A more permanant solution would be to use the advanced service authentication to request for an access token: 
 ```
    curl -k -X POST "https://aai.openaire.eu/oidc/token" \
    -d "grant_type=client_credentials" \
    -d "client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer" \
    -d "client_assertion={signedJWT}"
```
